= Usage
:page-pagination:

== Workflow

To test solutions with fenrir these steps are required:

. Install tests (optional)
. Select task
. Run tests


=== Install & select tests

`fenrir task <TASK ID>`

Installs the task from the remote repository. To check the repository run `fenrir i`.

If the task has been downloaded before, uses those sources. To update the sources use flag `--force`.

The selected task is shown in `fenrir i`.

=== Run tests

`fenrir run <SOLUTION DIR>`

CAUTION: The `SOLUTION DIR` must be a git repository!

.Options
* `-i`  --  do not clone the solution (default behaviour).
* `-nl`  --  skip linters
* `-c <TESTCASE>`  --  run only the selected testcase instead of the whole pipeline

You can run the tests in a docker container: `fenrir rund ..`

== Environment

`fenrir env up <DIR>`

Creates an environment for the task. When started, the env info is shown:

[,text]
----
  _____               _
 |  ___|__ _ __  _ __(_)_ __
 | |_ / _ \ '_ \| '__| | '__|
 |  _|  __/ | | | |  | | |
 |_|  \___|_| |_|_|  |_|_|

User:     fikus
Password: breach
System:   Alpine Linux v3.24
Task ID:  task0
----

To exit the env, run `exit`.

To destroy the env, run `fenrir env down`.

== Update & Uninstall

To update fenrir run `fenrir switch latest`.

To uninstall fenrir run `uninstall-fenrir`.
