#! /bin/bash

#repo=$1
verbosity=$2
branch=$3
destination=$(getroot)
out="/var/fenrir/out"
err="/var/fenrir/err"

##############

pushd "$destination" &> /dev/null

log info "$verbosity" "Switching branch to '$branch'"

if git switch "$branch" > "$out" 2> "$err"
then
    log succ "$verbosity" "Switched to '$branch'"
else
    log err "$verbosity" "Failed"
    log warn "$verbosity" "<stdout>" "$(cat "$out")"
    log err "$verbosity" "<stderr>" "$(cat "$err")"
    popd &> /dev/null
    exit 1
fi

popd &> /dev/null
