#! /usr/bin/env bash

repo=$1
verbosity=$2
destination="$HOME/solution"
out="/var/fenrir/out"
err="/var/fenrir/err"

##############

fenrir-log info "$verbosity" "Cloning repo $repo"

if [ -d "$destination" ]; then
    fenrir-log warn "$verbosity" "Remove previously cloned repo"
    rm -fr "$destination"
fi

if git clone "$repo" "$destination" > "$out" 2> "$err"
then
    fenrir-log succ "$verbosity" "Cloned repo to directory 'solution'"
else
    fenrir-log err "$verbosity" "Failed"
    fenrir-log warn "$verbosity" "<stdout>" "$(cat "$out")"
    fenrir-log err "$verbosity" "<stderr>" "$(cat "$err")"
    exit 1
fi

pushd "$destination" &> /dev/null
git switch task0 &> /dev/null
git switch "$(jq -r '.branch' "/etc/fenrir/main.json")" &> /dev/null

if [ "$(jq -r '.task' "/etc/fenrir/main.json")" = "git/ess" ]; then
    for i in $(seq 1 17); do
        git switch $i &> /dev/null
    done
fi
pod &> /dev/null

