#! /usr/bin/env bash

points=$1
score_file=$(jq -r '.score' "/etc/fenrir/main.json")

######################################################################

echo -n $(( points + $(cat "$score_file") )) > "$score_file"
