#! /bin/bash

verbosity=$1
#repo=$2
branch=$3


log info "$verbosity" "Checking whether branch <$branch> exists.."

if git branch | grep -q "$branch"; then
    log succ "$verbosity" "Branch exists"
else
    log err "$verbosity" "Branch does not exist"
    exit 1
fi
