#! /bin/bash

cmd=$1
shift

GREEN="\033[1m\033[38;5;112m"
BLUE="\033[1m\033[38;5;4m"
YELLOW="\033[1m\033[38;5;214m"
RED="\033[1m\033[38;5;196m"
ENDC="\033[0m"


function info {
    if [ "$1" = "-v" ]; then
        shift
        echo -e "${BLUE}[ INFO  ]${ENDC} $*" # > /dev/tty
    else
        echo "[ INFO  ] $*" # > /dev/tty
    fi
}

function warn {
    if [ "$1" = "-v" ]; then
        shift
        echo -e "${YELLOW}[WARNING]${ENDC} $*" # > /dev/tty
    else
        echo "[WARNING] $*" # > /dev/tty
    fi
}

function err {
    if [ "$1" = "-v" ]; then
        shift
        echo -e "${RED}[ ERROR ]${ENDC} $*" # > /dev/tty
    else
        echo "[ ERROR ] $*" # > /dev/tty
    fi
}

function succ {
    if [ "$1" = "-v" ]; then
        shift
        echo -e "${GREEN}[SUCCESS]${ENDC} $*" # > /dev/tty
    else
        echo "[SUCCESS] $*" # > /dev/tty
    fi
}


######################################################################

case "$cmd" in
    "warn")
        warn "$@"
        ;;
    "info")
        info "$@"
        ;;
    "err")
        err "$@"
        ;;
    "succ")
        succ "$@"
        ;;
    *)
        err -v "Command not found"
        exit 1
        ;;
esac
