#! /usr/bin/env bash

cmd=$1
shift

PURPLE="\033[1m\033[38;5;141m"
EMERALD="\033[1m\033[38;5;30m"
GRAY="\033[1m\033[38;5;249m"

GREEN="\033[1m\033[38;5;112m"
BLUE="\033[1m\033[38;5;4m"
YELLOW="\033[1m\033[38;5;214m"
RED="\033[1m\033[38;5;196m"
ENDC="\033[0m"

outf="/var/fenrir/out"
errf="/var/fenrir/err"

function info {
    if [ "$1" = "-v" ]; then
        shift
        echo -e "${BLUE}[ INFO  ]${ENDC} $*" # > /dev/tty
    else
        echo "[ INFO  ] $*" # > /dev/tty
    fi
}

function warn {
    if [ "$1" = "-v" ]; then
        shift
        echo -e "${YELLOW}[WARNING]${ENDC} $*" # > /dev/tty
    else
        echo "[WARNING] $*" # > /dev/tty
    fi
}

function err {
    if [ "$1" = "-v" ]; then
        shift
        echo -e "${RED}[ ERROR ]${ENDC} $*" # > /dev/tty
    else
        echo "[ ERROR ] $*" # > /dev/tty
    fi
}

function succ {
    if [ "$1" = "-v" ]; then
        shift
        echo -e "${GREEN}[SUCCESS]${ENDC} $*" # > /dev/tty
    else
        echo "[SUCCESS] $*" # > /dev/tty
    fi
}

function line {
    LINE="***----------------------------------------------------------------------------------***"

    if [ "$1" = "-v" ]; then
        echo -e "${GRAY}${LINE}${ENDC}"
    else
        echo "${LINE}"
    fi
}


######################################################################

case "$cmd" in
    "warn")
        warn "$@"
        ;;
    "info")
        info "$@"
        ;;
    "err")
        err "$@"
        ;;
    "succ")
        succ "$@"
        ;;
    "fail")
        err "$@"

        stdout_desc="| STDOUT ||  "
        stderr_desc="| STDERR ||  "

        line "$1"

        if [ "$1" = "-v" ]; then
            cat -- "$outf" | sed "s/^/$(echo -e "${EMERALD}${stdout_desc}${ENDC}")/"
        else
            cat -- "$outf" | sed "s/^/${stdout_desc}/"
        fi

        line "$1"

        if [ "$1" = "-v" ]; then
            cat -- "$errf" | sed "s/^/$(echo -e "${PURPLE}${stderr_desc}${ENDC}")/"
        else
            cat -- "$errf" | sed "s/^/${stderr_desc}/"
        fi

        line "$1"
        ;;
    *)
        err -v "Command not found"
        exit 1
        ;;
esac
