#! /usr/bin/env bash

######################################################################
##                         VERIFY ARGUMENTS                         ##
######################################################################

exp=0
real=$#

if [ "$exp" -ne "$real" ]; then
    fenrir-log err -v '(＃°Д°)' Wrong arguments count!
    fenrir-log err -v "Expected <$exp> but got <$real>"
    exit 15
fi

######################################################################
##                           MAIN PROGRAM                           ##
######################################################################

cat <<____HEREDOC
Possible options:
fenrir help

fenrir gc [-s]
fenrir remote <URL>
fenrir task [-s] <TASK ID>
fenrir run [-s] [--no-lint | -nl] [--no-zero | -nz] <SOLUTION DIR>

fenrir [-v|--version|version]
fenrir version
fenrir versions
fenrir switch [<VERSION> | latest]
------------------------------------------------------------------
fenrir help:
    Info about fenrir util
    See https://gitlab.com/atpd/progtech/fenrir

fenrir remote <URL>:
    Set remote task repository

fenrir task [-s] [-f|--force] <TASK ID>:
    Set task tests. If they have not been installed yet then install then.
    '-f' or '--force': Install anyway
    '-s': Mute colours

fenrir run [-s] [--no-lint|-nl] [--no-zero|-nz] <SOLUTION DIR>:
    Run local tests on the specified local repository
    '-s': Mute colours
    '--no-lint' or '-nl': Skip linters
    '--no-zero' or '-nz': Skip task0 tests

fenrir gc [-s]:
    Clean local repository. Removes all installed tasks and dependencies, fenrir-tmp.
    '-s': Soft mode. Removes only tmp & tag directories

fenrir versions:
    Get all available versions

fenrir switch [-s] latest:
    Update up to the latest version
    '-s': Mute colours

fenrir switch <VERSION>:
    Switch to the specified version (Error is thrown if the version is not available)
    Run 'fenrir version' to list all available versions

fenrir version:
    Print current version

fenrir [-v|--version|version]:
    Print current version
------------------------------------------------------------------
Current settings:
    * Remote: $(fenrir-getremote)
    * Solution branch: $(jq '.branch' '/etc/fenrir/main.json')
    * Blocking: $(jq '.blocking' '/etc/fenrir/main.json')
    * Last installed task: $(jq '.task' '/etc/fenrir/main.json')
------------------------------------------------------------------
Run settings:
$(jq . "$HOME/.fenrir/custom/pipeline.json")
------------------------------------------------------------------
fenrir $(jq '.version' '/etc/fenrir/main.json'), 2025
@_1BAH_
____HEREDOC


