#! /bin/bash

verbosity=$1
branch=$2
destination=$(fenrir-getroot)
out="/var/fenrir/out"
err="/var/fenrir/err"

##############

pushd "$destination" &> /dev/null

fenrir-log info "$verbosity" "Switching branch to '$branch'"

if git switch "$branch" > "$out" 2> "$err"
then
    fenrir-log succ "$verbosity" "Switched to '$branch'"
else
    fenrir-log err "$verbosity" "Failed"
    fenrir-log warn "$verbosity" "<stdout>" "$(cat "$out")"
    fenrir-log err "$verbosity" "<stderr>" "$(cat "$err")"
    popd &> /dev/null
    exit 1
fi

popd &> /dev/null
