image: ubuntu:latest

stages:
  - test
  - site

cache:
  paths:
    - node_modules

tests:
  stage: test
  before_script:
    - apt-get update && apt-get install -y wget
    - cd src/test/runtime
  script: ./run_tests.sh
  variables:
    FENRIR_IN_DOCKER: "-v"

pages:
  stage: site
  image: node:18.19.1
  script:
    - npm install
    - npx antora antora-playbook.yml
    - cp -r build/site public
    - ls -R public
  artifacts:
    paths:
      - public
  needs:
    - tests