include:
  - 'base-ci.yml'
  - 'docker-ci.yml'
  - 'fenrir-base.yml'
  - 'fenrir-dind.yml'


stages:
  - test
  - docker
  - site
  - tasks

pages:
  stage: site
  image: node:18.19.1
  script:
    - npm install
    - npx antora antora-playbook.yml
    - cp -r build/site public
    - ls -R public
  artifacts:
    paths:
      - public
  needs:
    - tests
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'



update-task-images:
  stage: tasks
  trigger:
    project: atpd/progtech/tech-tasks/gitlab-profile
  needs:
    - docker-latest
  rules:
    - if: '$CI_COMMIT_TAG'

update-task-images-manual:
  stage: tasks
  trigger:
    project: atpd/progtech/tech-tasks/gitlab-profile
  when: manual
