site:
  title: fenrir
  start_page: fenrir::index.adoc
content:
  sources:
    - url: https://gitlab.com/atpd/fenrir
      tags:
        - HEAD
        - v1.1.0
        - v1.0.0
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
