#! /usr/bin/env bash

cuser=$(
  pid=$$
  while [ -n "$pid" ] && [ "$pid" -gt 1 ] 2>/dev/null; do
    read -r ppid user < <(ps -o ppid=,user= -p "$pid" 2>/dev/null)

    if [ -n "$user" ] && [ "$user" != "root" ]; then
      echo "$user"
      break
    fi

    pid="$ppid"
  done
)
cuser=${cuser:-$(id -un)}
if [ "$cuser" = "root" ]; then
    FENRIR_HOME="/$cuser/.fenrir"
else
    FENRIR_HOME="/home/$cuser/.fenrir"
fi

if [ "$1" = "remove" ]; then # Remove (ignore update)
    echo "Uninstall fenrir work directories.."
    rm -fr "$FENRIR_HOME"
    rm -f "/home/$cuser/.oh-my-zsh/completions/_fenrir"
    rm -f "/etc/bash_completion.d/fenrir-autocomplete"
fi
