#! /usr/bin/env bash

# Load rc file:
source "/etc/fenrir/lokirc" &> /dev/null

set -T
set +m
shopt -s extdebug
shopt -s lastpipe

LOKI_COLUMNS=$(stty size 2> /dev/null || echo "foo 100")
LOKI_COLUMNS=${LOKI_COLUMNS#* }
LOKI_COLUMNS=$(( LOKI_COLUMNS - 10 )) # Add right padding

# Alternative TODO:complete docs!

#include <loki-common-const>
#include <loki-common-funs>

if [ "$1" = "-c" ]; then
    shift
    "$@"
    exit
fi

# IMPORTANT!! DO NOT USE 'JOTUNHEIM_..' AS A NAME FOR VARIABLES!!
JOTUNHEIM_LAST_CMD=""
JOTUNHEIM=()

# When no args, we just want to load all global functions and global consts
if (( $# != 0 )); then
    function save_cmd {
        # Sudo might occur during update
        if [ "$(id -u)" -eq 0 ]; then
            return 0
        fi

        if [[ "${BASH_SOURCE[1]}" == "/usr/local/bin/loki" ]]; then
            return 0
        fi

        # They are self-responsible for logging
        if [[ $BASH_COMMAND =~ ^loki.*$ || $BASH_COMMAND =~ ^fenrir.*$ ]] ; then
            return 0
        fi

        # Handle shadowing by other commands in subshells
        local JOTUNHEIM_CMD=${BASH_COMMAND}

        # Compute symmetric difference of two arrays
        local JOTUNHEIM_sym_diff
        JOTUNHEIM_sym_diff=$(echo "${JOTUNHEIM[@]}" "${FUNCNAME[@]}" | tr ' ' '\n' | sort | uniq -u)

        if [[ "${JOTUNHEIM_LAST_CMD}" == "${JOTUNHEIM_CMD}" ]]; then # INCORRECT FOR literal cmd duplications
            if [[ -z "${JOTUNHEIM_sym_diff}" ]] ||
               [[ "${JOTUNHEIM_CMD}" == "${FUNCNAME[1]}" ]]; then # INCORRECT FOR direct recursive call
                return 0
            fi
        fi

        local len=$(( ${#BASH_SOURCE[@]} - 1 ))
        {
            local func_name=${FUNCNAME[1]}
            if [[ "$func_name" == "source" ]]; then
                echo "[Script '${BASH_SOURCE[1]}']:"
            else
                echo "[Function '$(loki-wrap "${BOLD}" "${func_name}")'] at ${BASH_SOURCE[1]}:"
            fi

            # Avoid changing outer scope
            local JOTUNHEIM_i
            for (( JOTUNHEIM_i = 2; JOTUNHEIM_i < len; ++JOTUNHEIM_i )); do
                func_name=${FUNCNAME[JOTUNHEIM_i]}
                if [[ "$func_name" == "source" ]]; then
                    echo "  in [Script '${BASH_SOURCE[JOTUNHEIM_i]}']:"
                else
                    echo "  in [Function '$(loki-wrap "${BOLD}" "${func_name}")'] at ${BASH_SOURCE[JOTUNHEIM_i]}:"
                fi
            done

            if [ "$LOKI_VERBOSE" = "-v" ]; then
                sed "s|^|    ${MAGENTA}|; s|$|${ENDC}|" <<< "${JOTUNHEIM_CMD}"
            else
                echo -n "    "
                echo "${JOTUNHEIM_CMD}"
            fi
        } >> "$CMD_FILE"

        JOTUNHEIM_LAST_CMD="$JOTUNHEIM_CMD"
        JOTUNHEIM=("${FUNCNAME[@]}")
    }

    file=$(realpath "$1")
    other=("$@")
    other=("${other[@]:1}")

    if [ "$(id -u)" -ne 0 ] && [[ ! $(basename "$file") =~ ^fenrir.*$ ]]; then
        echo -n > "$CMD_FILE"
        trap 'save_cmd' DEBUG
    fi

    # shellcheck disable=SC1090
    source "$file" "${other[@]}"
fi
