#! /usr/bin/env bash

v="$1"
config="/etc/fenrir/walk.json"

fenrir-log info "$v" "WI: Start"

root_dir=$(fenrir-getroot)
reg_files_inspections=$(jq -r '.files[]' "$config")
dir_inspections=$(jq -r '.dirs[]' "$config")

function terminate {
    fenrir-log err "$v" "WI: terminate"
    exit 3
}

function dir_check {
    local dir=$1

    if [ "$(jq "isempty( .skip[] | select(. == \"$(basename "$dir")\") )" "$config")" = 'true' ]; then
        for inspection in $dir_inspections; do
            if ! "$HOME/.fenrir/custom/walk/$inspection" "$dir" "$v"; then
                terminate
            fi
        done

        inspect_dir "$dir"
#    else
#        fenrir-log info "mute" "WI: Skipping $dir" # muted
    fi
}

function inspect_dir {
    local dir=$1

    for file in "$dir"/* "$dir"/.*; do
        if [ -f "$file" ]; then
            for inspection in $reg_files_inspections; do
                if ! "$HOME/.fenrir/custom/walk/$inspection" "$file" "$v"; then
                    terminate
                fi
            done
        else
            if [ -d "$file" ]; then
                dir_check "$file"
            fi
        fi
    done
}

dir_check "$root_dir"

fenrir-log succ "$v" "WI: All inspections have passed"
