#! /usr/bin/env bash

echo "======================= Installing fenrir ======================="

#################################################################
#                        GLOBAL CONSTS                          #
#################################################################

CLI_DIR=${CLI_DIR:?"Cannot execute installer: 'CLI_DIR' was not provided"}
DOC_DIR=${DOC_DIR:?"Cannot execute installer: 'DOC_DIR' was not provided"}
FENRIR_DIR=$(realpath "${CLI_DIR}/..")
LOKI_DIR=$(realpath "${FENRIR_DIR}/../loki")

#################################################################
#                         VERIFY DIRS                           #
#################################################################

#include <install-verify-srcs>

#################################################################
#                       LOAD PROPERTIES                         #
#################################################################

while IFS='=' read -r key value; do
    case "$key" in
        version)
            VERSION=$value
            ;;
    esac
done < "$CLI_DIR/fenrir.properties"

if [[ $VERSION == "" ]]; then
    printf "\033[31m'VERSION' is not specified in properties! The sources might be broken!\033[0m\n" >& 2
    exit 5
fi

#################################################################
#                      PREPARE BUILD DIR                        #
#################################################################

BUILD_DIR="/tmp/FENRIR_BUILD"

if [ -d "$BUILD_DIR" ]; then
    rm -fr "$BUILD_DIR"
fi

mkdir -p "$BUILD_DIR/docs"

cp -r "$LOKI_DIR" "$BUILD_DIR/loki"
cp -r "$FENRIR_DIR" "$BUILD_DIR/fenrir"

# shellcheck disable=SC2164
pushd "$BUILD_DIR" &> /dev/null

echo "[ INFO  ] Now in BUILD_DIR: <$PWD>"

CORE_UTILS_DIR=$(realpath "${BUILD_DIR}/fenrir/core")
CFGS_DIR=$(realpath "${BUILD_DIR}/fenrir/configs")
BASIC_UTILS_DIR=$(realpath "${BUILD_DIR}/fenrir/shared")

#################################################################
#                       POST-VERIFY DIRS                        #
#################################################################

#include <install-verify-build>

# Load consts
source "${CFGS_DIR}/lokirc"

#################################################################
#                        DETERMINE USER                         #
#################################################################

[ -n "$SUDO_USER" ] && user=$SUDO_USER || user=$USER
echo "${BLUE}[ INFO  ]${ENDC} Installing ${SKY}fenrir@$VERSION${ENDC} for ${SKY}${user}${ENDC} user.."
echo "${BLUE}[ INFO  ]${ENDC} Build script is located in <$(realpath "$0")>"

#################################################################
#                     CREATE INSTALL DIRS                       #
#################################################################

echo "[ INFO  ] Creating <${FENRIR_CONF_DIR}>.."
mkdir -p "${FENRIR_CONF_DIR}"
chown "$user" "${FENRIR_CONF_DIR}"

#################################################################
#                    INSTALL 'LOKI' MODULE                      #
#################################################################

echo "[ INFO  ] Installing 'Loki' module.."

if ! [ -f "${FENRIR_CONF_DIR}/lokirc" ]; then
   echo "[ INFO  ] Installing default lokirc.."

    if ! cat "$CFGS_DIR/lokirc" > "${FENRIR_CONF_DIR}/lokirc"; then
        echo "[ ERROR ] Failed to install. Try again or submit an issue."
        exit 20
    fi
fi

#include <install-loki>

echo "[ INFO  ] Now switching to 'loki-log'.. (Colours might appear)"
loki-log succ "Loki is installed"

#################################################################
#                      INLINE FUNCTIONS                         #
#################################################################

#include <inline-funs>

#################################################################
#                       PARSE ARGUMENTS                         #
#################################################################

# TODO remove??
if [ -n "$IN_DOCKER" ]; then
    loki-log info "Running in a docker container"
fi

#################################################################
#                         DETERMINE OS                          #
#################################################################

loki-prog "Identifying OS.."
on_macos=""

case "$(uname -s)" in
    Linux*)
        os_pref_home="/home"
        loki-gorp "OS is $(loki-wrap "${BOLD}" "LINUX")"
    ;;
    Darwin*)
        on_macos=True
        os_pref_home="/Users"
        loki-gorp "OS is $(loki-wrap "${BOLD}" "MACOS")"
    ;;
#    CYGWIN*)
#        os=Cygwin
#    ;;
#    MINGW*)
#        os=MinGw
#    ;;
#    MSYS_NT*)
#        os=MSys
#    ;;
    *)
        loki-gorp "Unsupported OS: $(loki-wrap "${BOLD}" "$(uname -s)")"
        loki-log warn "Do you agree to continue? ($(loki-wrap "${BOLD}" Potentially dangerous)) [y|N]"

        read -r op
        if [ "$op" != "y" ] && [ "$op" != "Y" ]; then
            loki-log err "Terminating.."
            exit 6
        fi
    ;;
esac

#################################################################
#                   Check & clean filesystem                    #
#################################################################

loki-prog "Preparing environment.."

loki-prog "Working directories.."
if [ -d "${FENRIR_CONF_DIR}" ]; then
    find "${FENRIR_CONF_DIR}" -mindepth 1 -not -name "*.hel" | while read -r file; do
        [ "$(basename "$file")" = "lokirc" ] && continue

        rm -fr "$file"
        loki-log warn "File <$file> is removed"
    done
fi
loki-gorp

loki-prog "Previous installations.."
( # Variable scope: 'found' array
    [ -n "${FENRIR_TEST_MODE}" ] && exit 0

    found=()

    for cmd in "$CORE_UTILS_DIR"/*; do
        if ! [ -f "$cmd" ]; then
            continue
        fi

        name=$(basename "$cmd")
        if type "$name" &> /dev/null; then
            found+=("$(type "$name" | cut -d ' ' -f3)")
        fi
    done

    if [ -n "$IN_DOCKER" ]; then
        exit
    fi

    if [ "${#found[@]}" -eq 0 ]; then
        exit 0 # No conflicting files were detected
    fi

    # Alerts for out-of-docker installation
    loki-log warn "These commands already exist:"

    maxlen=0
    for cmd in "${found[@]}"; do
        thislen=$(basename "$cmd")
        thislen=${#thislen}
        maxlen=$(( maxlen < thislen ? thislen : maxlen ))
    done

    # shellcheck disable=SC2154
    for cmd in "${found[@]}"; do
        thislen=$(basename "$cmd")
        thislen=${#thislen}
        echo -n "'$(basename "$cmd")'$(loki-dup ' ' $(( maxlen - thislen )))"
        echo -n "  =>  "
        echo "'$cmd'"
    done | ${sed_cmd} "s/^/$(loki-wrap "${YELLOW}" "[WARNING]")      /"

    loki-log warn "They are to be replaced. Do you want to proceed? ($(loki-wrap "${BOLD}" Potentially dangerous)) [y|N]"

    read -r op
    if [ "$op" != "y" ] && [ "$op" != "Y" ]; then
        loki-log err "Terminating.."
        exit 7
    fi
) || exit $? # propagate error
loki-gorp

loki-prog "Cleaning local repo.."
if [ -n "${FENRIR_KEEP_LOCAL_REPO}" ]; then
    loki-log warn "'FENRIR_KEEP_LOCAL_REPO' is on: preserving the local repo"
else
    rm -fr "$os_pref_home/$user/.fenrir"
fi

loki-gorp

loki-gorp

#################################################################
#                        Install files                          #
#################################################################

#include <install-files>

#################################################################
#                          MAN PAGES                            #
#################################################################

#include <install-man>

###################################################################
#                       Finish installation                       #
###################################################################

if [ -z "${FENRIR_DEBUG_MODE}" ]; then
    rm -fr ${BUILD_DIR}
fi

loki-log succ "Installation has finished!"
