#! /bin/bash

cmd=$1
shift

######################################################################

function check_arg_count {
    exp=$1
    real=$2

    if [ "$exp" -ne "$real" ]; then
        fenrir-log err -v '(＃°Д°)' Wrong arguments count!
        fenrir-log err -v "Expected <$exp> but got <$real>"
        exit 15
    fi
}

function verify_non_sudo {
    if [ "$(id -u)" -eq 0 ]; then

        fenrir-log err -v 'ᕙ( •̀ ᗜ •́ )ᕗ' "The script must not be run under sudo!"
        exit 123
    fi
}

######################################################################

case "$cmd" in
    "remote")
        verify_non_sudo
        check_arg_count $# 1

        url=$1
        jq ".remote = \"$url\"" "/etc/fenrir/main.json" > /tmp/TMP_FENRIR
        cat /tmp/TMP_FENRIR > "/etc/fenrir/main.json"
    ;;

    "--help" | "-h" | "help")
        verify_non_sudo
        fenrir-info "$@"
    ;;

    "task")
        verify_non_sudo
        fenrir-task "$@"
    ;;

    "run")
        verify_non_sudo
        fenrir-run "$@"
    ;;

    "switch")
        verify_non_sudo
        update-fenrir "$@"
    ;;

    "versions")
        verify_non_sudo
        check_arg_count $# 0

        # FIXME: curl was not found!

        # TODO Handle errors
        tags=$(curl https://gitlab.com/api/v4/projects/67614102/repository/tags 2> /dev/null)
        echo "$tags" | jq '.[].name'
    ;;

    "-v" | "--version" | "version" | "-version")
        verify_non_sudo
        check_arg_count $# 0

        jq '.version' '/etc/fenrir/main.json'
    ;;

    "gc")
        verify_non_sudo
        fenrir-gc "$@"
    ;;

    *)
        fenrir-log err -v '(+_+)?' "Command not found"
        exit 1
    ;;
esac
