#! /bin/bash

cmd=$1
shift

######################################################################

url="https://gitlab.com/atpd/progtech/fenrir.git"
out="/var/fenrir/out"
err="/var/fenrir/err"

function save_tag_clone {
    tag=$1
    if ! git clone --depth 1 --branch "$tag" "$url" /tmp/fenrir > "$out" 2> "$err"; then
        fenrir-log err "Failed to clone repo"
        fenrir-log warn "<stdout>" "$(cat "$out")"
        fenrir-log err "<stderr>" "$(cat "$err")"
        exit 66
    fi
}

function save_clone {
    if ! git clone --depth 1 "$url" /tmp/fenrir > "$out" 2> "$err"; then
        fenrir-log err "Failed to clone repo"
        fenrir-log warn "<stdout>" "$(cat "$out")"
        fenrir-log err "<stderr>" "$(cat "$err")"
        exit 66
    fi
}


######################################################################

infolog="Possible options:
fenrir help
fenrir remote <URL>
fenrir task <TASK ID>
fenrir run <SOLUTION DIR>

fenrir versions
fenrir switch [<VERSION> | latest]
------------------------------------------------------------------
fenrir help:
    Info about fenrir util
    See https://gitlab.com/atpd/progtech/fenrir

fenrir remote <URL>:
    Set remote task repository

fenrir task <TASK ID>:
    Set task tests

fenrir run <SOLUTION DIR>:
    Run local tests on the specified local repository

fenrir versions
    Get all available versions

fenrir switch latest
    Update up to the latest version

fenrir switch <VERSION>
    Switch to the specified version (Error is thrown if the version is not available)
    Run 'fenrir version' to list all available versions
------------------------------------------------------------------
Current settings:
    * Remote: $(fenrir-getremote)
    * Solution branch: $(jq '.branch' '/etc/fenrir/main.json')
    * Blocking: $(jq '.blocking' '/etc/fenrir/main.json')
    * Last installed task: $(jq '.task' '/etc/fenrir/main.json')
------------------------------------------------------------------
Run settings:
$(jq . "$HOME/.fenrir/custom/pipeline.json")
------------------------------------------------------------------
fenrir $(jq '.version' '/etc/fenrir/main.json'), 2025
@_1BAH_"


function info {
    if [ "$#" -ne 0 ]; then
        fenrir-log err -v Too many arguments!
        exit 15
    fi

    echo "$infolog"
}

######################################################################

function get_index {
    host=$(fenrir-getremote)
    dir=$1

    wget -O /tmp/FENRIR_INDEX "$host/-/raw/main/$dir/index.json" &> /dev/null
    echo -n "*"
}

function get_custom {
    host=$(fenrir-getremote)
    dir=$1

    for script in $(jq -r .custom[] /tmp/FENRIR_INDEX); do
        wget -O "$HOME/.fenrir/custom/$script" "$host/-/raw/main/$dir/$script" &> /dev/null
        echo -n "*"
        chmod +x "$HOME/.fenrir/custom/$script"
    done
}

function get_cfgs {
    host=$(fenrir-getremote)
    dir=$1

    for script in $(jq -r .cfgs[] /tmp/FENRIR_INDEX); do
        wget -O "/etc/fenrir/$script" "$host/-/raw/main/$dir/$script" &> /dev/null
        echo -n "*"
    done
}

function get_pipeline {
    host=$(fenrir-getremote)
    dir=$1

    wget -O "$HOME/.fenrir/custom/pipeline.json" "$host/-/raw/main/$dir/pipeline.json" &> /dev/null
    echo -n "*"
}

function get_meta {
    branch=$(jq -r .branch /tmp/FENRIR_INDEX)
    jq ".branch = \"$branch\"" "/etc/fenrir/main.json" > /tmp/TMP_FENRIR
    cat /tmp/TMP_FENRIR > "/etc/fenrir/main.json"

    block=$(jq -r .blocking /tmp/FENRIR_INDEX)
    jq ".blocking = \"$block\"" "/etc/fenrir/main.json" > /tmp/TMP_FENRIR
    cat /tmp/TMP_FENRIR > "/etc/fenrir/main.json"
}

######################################################################

function install_tests {
    if [ "$#" -ne 1 ]; then
        fenrir-log err -v Too many arguments!
        exit 15
    fi

    task=$1

    echo -n "DOWNLOADING '$task' ["

    get_index "$task"

    get_meta
    get_cfgs "$task"
    get_custom "$task"
    get_pipeline "$task"

    echo "]"

    jq ".task = \"$task\"" "/etc/fenrir/main.json" > /tmp/TMP_FENRIR
    cat /tmp/TMP_FENRIR > "/etc/fenrir/main.json"
}

######################################################################

function set_remote {
    if [ "$#" -ne 1 ]; then
        fenrir-log err -v Too many arguments!
        exit 15
    fi

    url=$1
    jq ".remote = \"$url\"" "/etc/fenrir/main.json" > /tmp/TMP_FENRIR
    cat /tmp/TMP_FENRIR > "/etc/fenrir/main.json"
}

######################################################################

function run {
    if [ "$#" -ne 1 ]; then
        fenrir-log err -v Too many arguments!
        exit 15
    fi

    src=$(realpath "$1")

    if ! [ -d "$src/.git" ]; then
        fenrir-log err -v "The provided file is not a project root"
        exit 89
    fi

    jq ".root = \"$src\"" "/etc/fenrir/main.json" > /tmp/TMP_FENRIR
    cat /tmp/TMP_FENRIR > "/etc/fenrir/main.json"

    fenrir-main
}

######################################################################

function update {
    if [ "$#" -ne 1 ]; then
        fenrir-log err -v Too many arguments!
        exit 15
    fi

    tag=$1

    if [ "$tag" = "latest" ]; then
        save_clone
    elif [ -z "$tag" ]; then
        fenrir-log err "Empty version"
        exit 67
    else
        save_tag_clone "$tag"
    fi

    sudo uninstall-fenrir update
    sudo /tmp/fenrir/src/main/fenrir/cli/install-fenrir update

    rm -rf /tmp/fenrir

    fenrir-log succ -v "Successfully switched to '$(jq '.version' '/etc/fenrir/main.json') version"
}

######################################################################

function get_versions {
    if [ "$#" -ne 0 ]; then
        fenrir-log err -v Too many arguments!
        exit 15
    fi

    tags=$(curl https://gitlab.com/api/v4/projects/67614102/repository/tags 2> /dev/null)
    echo "$tags" | jq '.[].name'
}

######################################################################

sudo chmod -t /tmp

case "$cmd" in
    "remote")
        set_remote "$@"
    ;;

    "--help" | "-h" | "help")
        info "$@"
    ;;

    "task")
        install_tests "$@"
    ;;

    "run")
        run "$@"
    ;;

    "switch")
        update "$@"
    ;;

    "versions")
        get_versions "$@"
    ;;

    *)
        fenrir-log err "Command not found"
        exit 1
    ;;
esac

sudo chmod +t /tmp
