#! /usr/bin/env bash

out=(">" "/dev/null")
verbose=""

while (( $# > 0 )); do
    case "$1" in
    -v)
        out=()
        verbose="-v"
    ;;
    bash)
        export FENRIR_INSTALL_BASH=1
    ;;
    zsh)
        export FENRIR_INSTALL_ZSH=1
    ;;
    esac

    shift
done

#################################################################
#                         VERIFY SUDO                           #
#################################################################

if ! [ "$(id -u)" -eq 0 ]; then
    echo -e "\033[1m\033[38;5;196m[ ERROR ]\033[0m \033[38;5;197mᕙ( •̀ ᗜ •́ )ᕗ  \033[0mThe script must be run in a \033[1mprivileged mode\033[0m (sudo)!"
    exit 111
fi

echo "PROGRESS >> Assembling the build script.."

#################################################################
#                       ASSEMBLE INSTALLER                      #
#################################################################

CLI_DIR=$(dirname "$(realpath "$0")") # 'cli' directory
BUILD_SCRIPT="/tmp/FENRIR_BUILD_SCRIPT"

if [ -f "$BUILD_SCRIPT" ]; then
    eval "echo \"[ INFO  ] Found an old build script: <$BUILD_SCRIPT>\" ${out[*]}"
    rm -fr "$BUILD_SCRIPT" &> /dev/null
fi



( # Do not pollute the global variable scope
    first=1
    for script in "${CLI_DIR}"/install/*; do
        if [[ $script == "install-fenrir" ]]; then
            continue
        fi

        eval "echo \"[ INFO  ] Inlining module <$script>..\" ${out[*]}"

        file=$(basename "$script")
        pattern="#include <$file>"

        if (( first == 1 )); then
            sed -e "/$pattern/r $script" -e "/$pattern/d" "${CLI_DIR}"/install/install-fenrir > $BUILD_SCRIPT
            first=0
        else
            sed -i -e "/$pattern/r $script" -e "/$pattern/d" $BUILD_SCRIPT
        fi
    done
)

chmod +x $BUILD_SCRIPT

eval "echo \"[ INFO  ] The final build script is <$BUILD_SCRIPT>\" ${out[*]}"
echo "PROGRESS << DONE"

CLI_DIR="$CLI_DIR" FENRIR_INSTALL_VERBOSE="$verbose" LOKI_VERBOSE="$verbose" $BUILD_SCRIPT
