#! /usr/bin/env bash

out=(">" "/dev/null")
verbose=""
sed_cmd="sed"
out_dir="/usr/local/bin"
conf_dir="/etc/fenrir"

while (( $# > 0 )); do
    case "$1" in
    -v)
        out=()
        verbose="-v"
    ;;
    bash)
        export FENRIR_INSTALL_BASH=1
    ;;
    zsh)
        export FENRIR_INSTALL_ZSH=1
    ;;
    --install-dir)
        out_dir="$2"
        shift
    ;;
    --conf-dir)
        conf_dir="$2"
        shift
    ;;
    -t)
        test_mode=True
    ;;
    esac

    shift
done

eval "echo \"[ INFO  ] Install dir is: <${out_dir}>\" ${out[*]}"
eval "echo \"[ INFO  ] Config dir is: <${conf_dir}>\" ${out[*]}"
#################################################################
#                    CHECK EXISTING CONFIGS                     #
#################################################################

if [ -f "${conf_dir}/main.hel" ]; then
    eval "echo \"[ INFO  ] Found existing configs: <${conf_dir}/main.hel>\" ${out[*]}"

    case "$(grep -oP 'complete="\K[^"]*' "${conf_dir}/main.hel")" in
        bash)
            eval "echo \"[ INFO  ] Bash autocompletion to be installed\" ${out[*]}"
            export FENRIR_INSTALL_BASH=1
        ;;
        zsh)
            eval "echo \"[ INFO  ] Zsh autocompletion to be installed\" ${out[*]}"
            export FENRIR_INSTALL_ZSH=1
        ;;
        *)
            eval "echo \"[ WARN  ] Autocomplete: Unknown option\" ${out[*]}"
        ;;
    esac
fi

sed --help &> /dev/null || {
    echo -e "\033[1m\033[38;5;214m[ WARN  ]\033[0m \033[38;5;209m(シ. .)シ  \033[0mYou use BSD's version of sed!"

    which gsed &> /dev/null || {
        echo -e "\033[1m\033[38;5;196m[ ERROR ]\033[0m \033[38;5;197mᕙ( •̀ ᗜ •́ )ᕗ  \033[0mInstall 'gsed': brew install gnu-sed!"
        exit 111
    }

    sed_cmd="gsed"
    echo -e "\033[1m\033[38;5;214m[ WARN  ]\033[0m \033[38;5;209m(シ. .)シ  \033[0mNow using 'gsed' instead!"
}

export sed_cmd

#################################################################
#                         VERIFY SUDO                           #
#################################################################
if [ -n "$test_mode" ]; then
    echo -e "\033[1m\033[38;5;214m[ WARN  ]\033[0m \033[38;5;209m\(˚☐˚)/  \033[0mTest mode is on!"

    [ -d "${out_dir}" ] || mkdir -p "${out_dir}"
    [ -d "${conf_dir}" ] || mkdir -p "${conf_dir}"
elif ! [ "$(id -u)" -eq 0 ]; then
    echo -e "\033[1m\033[38;5;196m[ ERROR ]\033[0m \033[38;5;197mᕙ( •̀ ᗜ •́ )ᕗ  \033[0mThe script must be run in a \033[1mprivileged mode\033[0m (sudo)!"
    exit 111
else
    [ -d "${out_dir}" ] || {
        echo -e "\033[1m\033[38;5;196m[ ERROR ]\033[0m \033[38;5;197mᕙ( •̀ ᗜ •́ )ᕗ  \033[0mThe install dir <${out_dir}> does not exist!"
        exit 112
    }

    [ -d "${conf_dir}" ] || {
        echo -e "\033[1m\033[38;5;196m[ ERROR ]\033[0m \033[38;5;197mᕙ( •̀ ᗜ •́ )ᕗ  \033[0mThe config dir <${conf_dir}> does not exist!"
        exit 113
    }
fi

echo "PROGRESS >> Assembling the build script.."

#################################################################
#                       ASSEMBLE INSTALLER                      #
#################################################################

CLI_DIR=$(dirname "$(realpath "$0")") # 'cli' directory
BUILD_SCRIPT="/tmp/FENRIR_BUILD_SCRIPT"

if [ -f "$BUILD_SCRIPT" ]; then
    eval "echo \"[ INFO  ] Found an old build script: <$BUILD_SCRIPT>\" ${out[*]}"
    rm -fr "$BUILD_SCRIPT" &> /dev/null
fi



( # Do not pollute the global variable scope
    first=1
    for script in "${CLI_DIR}"/install/*; do
        if [[ $script == "install-fenrir" ]]; then
            continue
        fi

        eval "echo \"[ INFO  ] Inlining module <$script>..\" ${out[*]}"

        file=$(basename "$script")
        pattern="#include <$file>"

        if (( first == 1 )); then
            ${sed_cmd} -e "/$pattern/r $script" -e "/$pattern/d" "${CLI_DIR}"/install/install-fenrir > $BUILD_SCRIPT
            first=0
        else
            ${sed_cmd} -i -e "/$pattern/r $script" -e "/$pattern/d" $BUILD_SCRIPT
        fi
    done
)

chmod +x $BUILD_SCRIPT

eval "echo \"[ INFO  ] The final build script is <$BUILD_SCRIPT>\" ${out[*]}"
echo "PROGRESS << DONE"

CLI_DIR="$CLI_DIR" \
FENRIR_INSTALL_VERBOSE="$verbose" \
LOKI_VERBOSE="$verbose" \
FENRIR_INSTALL_DIR="$out_dir" \
FENRIR_CONF_DIR="$conf_dir" \
FENRIR_TEST_MODE="$test_mode" \
$BUILD_SCRIPT

res=$?

rm -fr "$BUILD_SCRIPT" &> /dev/null
exit $res

