#! /usr/bin/env bash

[ -n "$SUDO_USER" ] && user=$SUDO_USER || user=$USER

###################################################################

GREEN="\033[38;5;112m"
BLUE="\033[38;5;4m"
YELLOW="\033[38;5;214m"
RED="\033[38;5;196m"
ENDC="\033[0m"


function info {
    [ -n "${FENRIR_IN_DOCKER}" ] || echo -e "${BLUE}[ INFO  ]${ENDC} $*"
}

function warn {
    [ -n "${FENRIR_IN_DOCKER}" ] || echo -e "${YELLOW}[WARNING]${ENDC} $*"
}

function err {
    [ -n "${FENRIR_IN_DOCKER}" ] || echo -e "${RED}[ ERROR ]${ENDC} $*"
}

function succ {
    [ -n "${FENRIR_IN_DOCKER}" ] || echo -e "${GREEN}[SUCCESS]${ENDC} $*"
}

FENRIR_TMP_DIR=${FENRIR_TMP_DIR:-"/tmp/fenrir/tmp"}
FENRIR_HOME=${FENRIR_HOME:-"/home/$user/.fenrir"}

#################################################################

version=$(fenrir-read-conf main version)

if [ -n "${FENRIR_IN_DOCKER}" ]; then
    echo "[ INFO  ] Uninstalling previous version of fenrir: ${version}"
else
    info "Uninstalling previous version of fenrir: ${version}"
fi

#################################################################

if [ "$(id -u)" -ne 0 ]; then
    err "The script must be run under sudo!"
    exit 111
fi

#################################################################

info "Removing working directories.."

if [ -d "${FENRIR_TMP_DIR}" ]; then
    rm -r "${FENRIR_TMP_DIR}"
else
    warn "fenrir's tmp directory was not found!"
fi

if [ -d "${FENRIR_HOME}" ]; then
    rm -r "${FENRIR_HOME}"
else
    warn "fenrir's local repository was not found!"
fi

succ "Done"

#################################################################

info "Removing '/etc/fenrir'.."

if [ -d "/etc/fenrir" ]; then
    rm -r /etc/fenrir
else
    warn "The directory does not exist!"
fi

succ "Done"

#################################################################

info "Removing Loki.."

if [ -f "/usr/local/bin/loki" ]; then
    rm -fr "/usr/local/bin/loki"
else
    warn "'loki' binary was not find"
fi

succ "Done"

#################################################################

info "Removing core.."

for cmd in /usr/local/bin/fenrir-*; do
    if [ "$cmd" = "/usr/local/bin/fenrir-*" ]; then
        warn "No core commands were found!"
        break
    fi

    if ! rm "$cmd"; then
        err "Terminating.."
        exit 10
    fi
done

if [ -f "/usr/local/bin/update-fenrir" ]; then
    rm "/usr/local/bin/update-fenrir"
fi

succ "Done"

#################################################################

info "Removing cli tool.."

if [ -f "/usr/local/bin/fenrir" ]; then
    rm "/usr/local/bin/fenrir"
else
    warn "fenrir cli is not installed"
fi

succ "Done"

# Remove the script itself
rm -fr "/usr/local/bin/uninstall-fenrir"
