#! /bin/bash

# ASSUMPTION: running from src/test/core
#test_env_dir=$(cat TEST_ENV_DIR)


export PATH=$(cat PATH_NEW)


function info {
    fenrir-log info -v "$@"
}

function warn {
    fenrir-log warn -v "$@"
}

function err {
    fenrir-log err -v "$@"
}

function succ {
    fenrir-log succ -v "$@"
}

return_code=0

cat <<__HEREDOC
==================================================================
                          Running tests
==================================================================
__HEREDOC

ls -R

for test_file in ../*Tests.sh; do
    if [ -d "../$test_file" ]; then
        continue
    fi

    echo "$test_file"

    if ! "$test_file"; then
        err "Test failed"
        (( return_code++ ))
    else
        succ "Test passed"
    fi

    echo "=================================================================="
done
