name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: 'Version to be released'
  push:
    tags:
      - 'v*'

env:
  version: 2026.0 #${{ github.ref_name }}${{ inputs.version }}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get install rpm make asciidoctor

      - name: Create packages
        run:
          make -j$(nproc) all

      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.version }}
          release_name: "Fenrir ${{ env.version }}"

      - name: Publish deb package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /home/runner/fenrir-${{ env.version }}.noarch.deb
          asset_content_type: application/vnd.debian.binary-package
          asset_name: fenrir-${{ env.version }}.noarch.deb

      - name: Publish rpm package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /home/runner/fenrir-${{ env.version }}.noarch.rpm
          asset_content_type: application/x-rpm
          asset_name: fenrir-${{ env.version }}.noarch.rpm
